# Universidad de La Laguna
# Escuela Superior de Ingeniería y Tecnología
# Grado en Ingeniería Informática
# Asignatura: Algoritmos y Estructuras de Datos Avanzados
# Curso: 2º
# Práctica 4: Búsqueda por dispersión
# Autor: Paula María Darias Sosa
# Correo: alu0101398594@ull.es
# Fecha: 20/03/2023
CC=g++
CXXFLAGS= -std=c++17 -g

OBJS= main.o
all: ${OBJS}
	$(CC) $(CXXFLAGS) -o p4_AyEDA ${OBJS}

clean:
	rm -rf *.o p4_AyEDA