# Universidad de La Laguna
# Escuela Superior de Ingeniería y Tecnología
# Grado en Ingeniería Informática
# Asignatura: Algoritmos y Estructuras de Datos Avanzados
# Curso: 2º
# Práctica 5: Implementación de métodos de ordenación
# Autor: Paula María Darias Sosa
# Correo: alu0101398594@ull.es
# Fecha: 17/04/2023
CC=g++
CXXFLAGS= -std=c++17 -g

OBJS= main.o
all: ${OBJS}
	$(CC) $(CXXFLAGS) -o p5_AyEDA ${OBJS}

clean:
	rm -rf *.o p5_AyEDA