# Universidad de La Laguna
# Escuela Superior de Ingeniería y Tecnología
# Grado en Ingeniería Informática
# Asignatura: Algoritmos y Estructuras de Datos Avanzados
# Curso: 2º
# Práctica 2: Calculadora de números grandes en binario
# Autor: Paula María Darias Sosa
# Correo: alu0101398594@ull.es
# Fecha: 25/02/2023
CC=g++
CXXFLAGS= -Wall -std=c++17 -g

OBJS= main.o
all: ${OBJS}
	$(CC) $(CXXFLAGS) -o p2_AyEDA ${OBJS}

clean:
	rm -rf *.o p2_AyEDA