# Universidad de La Laguna
# Escuela Superior de Ingeniería y Tecnología
# Grado en Ingeniería Informática
# Asignatura: Algoritmos y Estructuras de Datos Avanzados
# Curso: 2º
# Práctica 3: Calculadora universal para números enteros grandes
# Autor: Paula María Darias Sosa
# Correo: alu0101398594@ull.es
# Fecha: 6/03/2023
CC=g++
CXXFLAGS= -std=c++17 -g

OBJS= main.o
all: ${OBJS}
	$(CC) $(CXXFLAGS) -o p3_AyEDA ${OBJS}

clean:
	rm -rf *.o p3_AyEDA